### ISSUE TITLE
apt-get install picamera gives error

### ISSUE THREAD

**Issue by R4C3R** [zoroloco/boothy#3]
`apt-get install picamera` gives an error I think it should be `apt-get install python-picamera`

maybe you could change install.txt like this (adding the -y option makes that you can copy & paste it in the terminal for any quick & easy installation):

apt-get update && apt-get upgrade -y
apt-get install cups python-cups python-picamera defoma xrdp imagemagick python-dev python-rpi.gpio matchbox-keyboard -y

**Comment by zoroloco** [comment]
done. Thanks for the suggestion.
