### ISSUE TITLE
Can't start the programme

### ISSUE THREAD

**Issue by jul1792** [zoroloco/boothy#4]
Hi there,

I installed everything but when I run `/usr/local/src/boothy/run.sh` it gives me this error:

`2018-07-03 22:40:21,047 - INFO - Initializing camera.
2018-07-03 22:40:21,284 - INFO - Starting preview
2018-07-03 22:40:21,369 - ERROR - Unhandled exception : 
Traceback (most recent call last):
  File "/usr/local/src/boothy/pbooth.py", line 208, in <module>
    addPreviewOverlay(20,200,55,"Press red button to begin!")
  File "/usr/local/src/boothy/pbooth.py", line 104, in addPreviewOverlay
    overlay_renderer = camera.add_overlay(img.tostring(),
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 697, in tostring
    "Please call tobytes() instead.")
NotImplementedError: tostring() has been removed. Please call tobytes() instead.
2018-07-03 22:40:21,437 - INFO - quitting...
/usr/local/src/boothy/pbooth.py:75: RuntimeWarning: No channels have been set up yet - nothing to clean up!  Try cleaning up at the end of your program instead!
  GPIO.cleanup()
>>> `

This is my setup:

- Raspberry Pi 3 with Raspbian Stretch
- PiCamera V2
- Canon Selphy CP800
- [This 7" TFT LC Display ](https://www.pollin.de/p/7-17-78-cm-display-set-ls-7-hdmi-dvi-vga-cvbs-120942)
- [This Red Button](https://www.amazon.de/gp/product/B01LZMANZ7/ref=oh_aui_detailpage_o02_s00?ie=UTF8&psc=1) 
- [These Jumper Wires and Breadboard ](https://www.amazon.de/gp/product/B071RG9MFT/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1)

[I used this guide to build my photobooth.](https://www.wikihow.com/Create-a-Photo-Booth-with-the-Raspberry-Pi)

I hope you can help my to get it running.

Thanks!

**Comment by zoroloco** [comment]
Looks like picamera v1.10 uses image.toString() for the add_overlay method, but the newer version of picamera (v1.13) uses image.toBytes().  I wrote my photobooth software with picamera version 1.10.  Looks like you have 1.13.    Try changing line 104 to: overlay_renderer = camera.add_overlay(img.**tobytes()**,layer=3,
                                              size=img.size,
                                              alpha=128);
If that does not work, then use picamera version 1.10.  Thanks.

**Comment by jul1792** [comment]
Thanks for your answer!
In which file should I change the line 104?

**Comment by jul1792** [comment]
Hi again,
I found the dilemmas changed the line, but that didn‘t solve the problem. 
Can you tell me how I can install the version 1.10? 
When I just follow the instructions from the picamera github site, I will install the latest version which is not 1.10..
Thanks a lot in advance!
